#!/bin/sh

SOURCETYPE="AUR"
SOURCEPATH="https://aur.archlinux.org/packages/ap/apache-tools/apache-tools.tar.gz"

function GetSourcePatch {
	sed -i "s/^arch=(i686 x86_64)/arch=(i686 x86_64 arm armv6h armv7h)/g" PKGBUILD
}

