#!/bin/sh

SOURCETYPE="AUR4"
SOURCEPATH="https://aur.archlinux.org/targetcli-fb.git"

function GetSourcePatch {
	sed -i "s/^makedepends=('python-setuptools')/makedepends=('python-setuptools' 'python-pyudev')/g" PKGBUILD
}
