#!/bin/sh

SOURCETYPE="AUR"
SOURCEPATH="https://aur.archlinux.org/packages/vl/vlc-htsp-plugin-git/vlc-htsp-plugin-git.tar.gz"

function GetSourcePatch {
	sed -i "s/^arch=('i686' 'x86_64')/arch=('i686' 'x86_64' 'arm' 'armv6h' 'armv7h')/g" PKGBUILD
}

