#!/bin/sh

SOURCETYPE="AUR4"
SOURCEPATH="https://aur.archlinux.org/vlc-htsp-plugin-git.git"

GetSourcePatch() {
	sed -i "s/^arch=('i686' 'x86_64')/arch=('i686' 'x86_64' 'arm' 'armv6h' 'armv7h')/g" PKGBUILD
}

