#!/bin/sh

SOURCETYPE="AUR"
SOURCEPATH="https://aur.archlinux.org/packages/an/android-google-play-apk-expansion/android-google-play-apk-expansion.tar.gz"

function GetSourcePatch {
	sed -i "s/^arch=('any')/arch=('i686' 'x86_64')/g" PKGBUILD
}

