#!/bin/sh

SOURCETYPE="AUR"
SOURCEPATH="https://aur.archlinux.org/packages/tv/tvheadend-git/tvheadend-git.tar.gz"

function GetSourcePatch {
	sed -i "s/^arch=('i686' 'x86_64')/arch=('i686' 'x86_64' 'arm' 'armv6h' 'armv7h')/g" PKGBUILD
	sed -i "s/^depends=('avahi' 'openssl' 'python2')/depends=('avahi' 'openssl' 'python2' 'uriparser' 'ffmpeg')/g" PKGBUILD
	sed -i "s/^makedepends=('git')/makedepends=('git' 'java-runtime')/g" PKGBUILD
	sed -i "s/^	'ffmpeg-compat: for transcoding support')/)/g" PKGBUILD
	sed -i "s#if \[ -d \"/usr/include/ffmpeg-compat\" \]; then#if \[ 0 = 1 \]; then#g" PKGBUILD
}
