#!/bin/sh

LOCALPKGVER="N"
SOURCETYPE="AUR"
SOURCEPATH="https://aur.archlinux.org/packages/no/noip/noip.tar.gz"

function GetSourcePatch {
	sed -i "s/^arch=('x86_64' 'i686' 'armv7h' 'armv6h')/arch=(\"i686\" \"x86_64\" \"arm\" \"armv6h\" \"armv7h\")/g" PKGBUILD
}

