#!/bin/sh

SOURCETYPE="AUR"
SOURCEPATH="https://aur.archlinux.org/packages/an/android-google-play-billing/android-google-play-billing.tar.gz"

GetSourcePatch() {
	sed -i "s/^arch=('any')/arch=('i686' 'x86_64')/g" PKGBUILD
}

