#!/bin/sh

SOURCETYPE="AUR4"
SOURCEPATH="https://aur4.archlinux.org/multipath-tools.git"

function GetSourcePatch {
	sed -i "s/^arch=('i686' 'x86_64')/arch=('i686' 'x86_64' 'arm' 'armv6h' 'armv7h')/g" PKGBUILD
}

