#!/bin/sh

SOURCETYPE="AUR"
SOURCEPATH="https://aur.archlinux.org/packages/mu/multipath-tools/multipath-tools.tar.gz"

function GetSourcePatch {
	sed -i "s/^arch=('i686' 'x86_64')/arch=('i686' 'x86_64' 'arm' 'armv6h' 'armv7h')/g" PKGBUILD
}

